-- Remove all vanilla difficulty-based traits that affect humans
DELETE FROM TraitModifiers WHERE 
ModifierId = 'BARBARIAN_CAMP_GOLD_SCALING' OR 
ModifierId = 'LOW_DIFFICULTY_COMBAT_SCALING' OR 
ModifierId = 'LOW_DIFFICULTY_UNIT_XP_SCALING' ;

/* Here are the difficulty-based traits that affect the AI
ModifierId = 'HIGH_DIFFICULTY_SCIENCE_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_CULTURE_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_PRODUCTION_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_GOLD_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_FAITH_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_COMBAT_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_UNIT_XP_SCALING' OR 
ModifierId = 'HIGH_DIFFICULTY_FREE_TECH_BOOSTS' OR 
ModifierId = 'HIGH_DIFFICULTY_FREE_CIVIC_BOOSTS' ;
*/

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_MAJOR_CIV', 'BM_DIFFICULTY_COMBAT_STRENGTH_SCALING_FOR_HUMANS') ;

INSERT INTO Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) VALUES 
('BM_DIFFICULTY_COMBAT_STRENGTH_SCALING_FOR_HUMANS', 'MODIFIER_PLAYER_UNITS_ADJUST_COMBAT_DIFFICULTY', 'PLAYER_IS_HUMAN') ;

INSERT INTO ModifierArguments (ModifierId, Name, Type, Value, Extra, SecondExtra) VALUES 
('BM_DIFFICULTY_COMBAT_STRENGTH_SCALING_FOR_HUMANS', 'Amount', 'LinearScaleFromDefaultHandicap', 0, -1, 'DIFFICULTY_DEITY') ;

INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES
('BM_DIFFICULTY_COMBAT_STRENGTH_SCALING_FOR_HUMANS', 'Preview', 'LOC_BM_DIFFICULTY_COMBAT_STRENGTH_SCALING_FOR_HUMANS_PREVIEW') ;